# src/main/resources/application.properties
spring.application.name=LocalRideAssistantServer
spring.datasource.url=jdbc:postgresql://localhost:5432/localride?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=100%Kfz
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Flyway Database Migration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Server Port
server.port=8081

# Logging Level for Spring Security and related components
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

# CORS Configuration
jwt.secret=YourSuperSecretKeyForJWTGenerationAndValidationWhichShouldBeLongEnoughAndRandom
# JWT Configuration 24 hours in milliseconds
jwt.expiration=86400000