spring.application.name=LocalRideAssistantServer
spring.datasource.url=jdbc:postgresql://localhost:5432/localride
spring.datasource.username=postgres
spring.datasource.password=100%Kfz
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration